{
 "title": "05. CMS Solar Park Wise Comparison",
 "tags": [ "CMS" ],
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Thandon Infrastructure Pvt. Ltd – Plant wise Cumulative Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "PMPPL_Block01 ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_did",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "query": "SELECT last(\"value\")  / 10 FROM \"wattmon_std_mv\" WHERE (\"did\" = 'HTmeter' AND \"f\" = 'kW_Total_Export' AND \"dlid\" = '9C956E78E3E0') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dlid", "operator": "=", "value": "44B7D09EA775" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
     ]
    }
   ]
  },
  {
   "title": "PMPPL Block02",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_did",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "query": "SELECT last(\"value\")  / 10 FROM \"wattmon_std_mv\" WHERE (\"did\" = 'HTmeter' AND \"f\" = 'kW_Total_Export' AND \"dlid\" = '9C956E78E3E0') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
     ]
    }
   ]
  },
  {
   "title": "PSPPL MUTTAGI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_did",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "query": "SELECT last(\"value\")  / 10 FROM \"wattmon_std_mv\" WHERE (\"did\" = 'HTmeter' AND \"f\" = 'kW_Total_Export' AND \"dlid\" = '9C956E78E3E0') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dlid", "operator": "=", "value": "44B7D09EA719" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
     ]
    }
   ]
  },
  {
   "title": "PSPPL INDI",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_did",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "query": "SELECT last(\"value\")  / 10 FROM \"wattmon_std_mv\" WHERE (\"did\" = 'HTmeter' AND \"f\" = 'kW_Total_Export' AND \"dlid\" = '9C956E78E3E0') AND $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
     ]
    }
   ]
  },
  {
   "title": "Thandon Infrastructure Pvt. Ltd – Inveter Power",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "alias": "$tag_did ",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA775" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "alias": "$tag_did ",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "alias": "$tag_did ",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA719" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "timeseries",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "targets": [
      {
       "alias": "$tag_did ",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " / 1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Infrastructure Pvt. Ltd - Inverter Energy (kWh)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1d,-330m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA775" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did ",
       "groupBy": [
        { "params": [ "1d-330m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1d,-330m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA719" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 12, "x": 12, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1d,-330m" ], "type": "time" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"v\" WHERE (\"d\" = 'WEATHER-STATION' AND \"f\" = 'PYRO_TILT' AND \"bd\" = 'maharastra_20MW') AND $timeFilter GROUP BY time(5m), \"f\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Infrastructure Pvt. Ltd - Inverter Status Code Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 13, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Status_Code" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 11, "x": 13, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Status_Code" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 13, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Status_Code" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "bargauge",
     "gridPos": { "h": 20, "w": 11, "x": 13, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Status_Code" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Park Hourly Energy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "barchart",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      },
      {
       "alias": "Expected Solar Energy (kWh)",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " *6947" ], "type": "math" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "9C956E78E3E9" },
        { "condition": "AND", "key": "did", "operator": "=", "value": "kWh" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      },
      {
       "alias": "Expected Solar Energy (kWh)",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " *6947" ], "type": "math" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "9C956E78E3E9" },
        { "condition": "AND", "key": "did", "operator": "=", "value": "kWh" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "barchart",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" }
       ]
      },
      {
       "alias": "Expected Solar Energy (kWh)",
       "groupBy": [
        { "params": [ "1h, -330m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         {
          "params": [],
          "type": "non_negative_difference"
         },
         { "params": [ " *6947" ], "type": "math" }
        ]
       ],
       "tags": [
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "9C956E78E3E9" },
        { "condition": "AND", "key": "did", "operator": "=", "value": "kWh" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Park -String Current Comparison",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA775" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=~", "value": "/.*Current_String*./" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=~", "value": "/.*Current_String*./" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "table",
     "gridPos": { "h": 21, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "44B7D09EA719" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=~", "value": "/.*Current_String*./" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "table",
     "gridPos": { "h": 22, "w": 24, "x": 0, "y": 69 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "1d, -330m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" },
        { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=~", "value": "/.*Current_String*./" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Park -Specific Power Summary ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Iv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Iv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Iv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Iv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "AC_Active_Power" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Thandon Park  Specific Yield Inverter wise (kWh/kW)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "PMPPL BLOCK01",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
       ]
      }
     ]
    },
    {
     "title": "PMPPL BLOCK02",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 11, "x": 13, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL MUTTAGI",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 13, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
       ]
      }
     ]
    },
    {
     "title": "PSPPL INDI",
     "type": "bargauge",
     "gridPos": { "h": 19, "w": 11, "x": 13, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "$tag_did",
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "did" ], "type": "tag" },
        { "params": [ "f" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "wattmon_std_mv",
       "query": "SELECT last(\"value\") FROM \"scaback_csv\" WHERE (\"d\" = 'EM02' AND \"f\" = 'PAC') AND value < 5000 AND $timeFilter GROUP BY time(1m) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ " /300" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "did", "operator": "=~", "value": "/.*Inv*./" },
        { "condition": "AND", "key": "f", "operator": "=", "value": "kWh_Day_Active" },
        { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
       ]
      }
     ]
    }
   ]
  }
 ]
}