{
 "title": "13.Fleet wise - Downloadable Reports",
 "tags": [ "CMS" ],
 "time": { "from": "now/M", "to": "now" },
 "panels": [
  {
   "title": "Fleet Wise -Daily Generation Reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Site Wise Actual Vs Target (kWh)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Anagodu - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
     ]
    },
    {
     "alias": "Anagodu-2 -$tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
     ]
    },
    {
     "alias": "Muttagi -$tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
     ]
    },
    {
     "alias": "Indi- $tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
     ]
    },
    {
     "alias": "Anagodu Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *12910" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2D57" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
     ]
    },
    {
     "alias": "Muttagi Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *6451" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90F9824B1" }
     ]
    },
    {
     "alias": "Indi Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *6851" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90FAFFAB3" }
     ]
    }
   ]
  },
  {
   "title": "Fleet Wise Inverter Generation (kWh)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Anagodu - $tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
     ]
    },
    {
     "alias": "Anagodu -$tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
     ]
    },
    {
     "alias": "Muttagi -$tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
     ]
    },
    {
     "alias": "Indi- $tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
     ]
    }
   ]
  },
  {
   "title": "Day Wise Insolation (kWh/m^2)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Anagodu - $tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2D57" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
     ]
    },
    {
     "alias": "Muttagi - $tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90F9824B1" }
     ]
    },
    {
     "alias": "Indi - $tag_did",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90FAFFAB3" }
     ]
    }
   ]
  },
  {
   "title": "Site Wise Actual Vs Target (kWh)",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "alias": "Anagodu - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA775" }
     ]
    },
    {
     "alias": "Anagodu-2 -$tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA7C2" }
     ]
    },
    {
     "alias": "Muttagi -$tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "44B7D09EA719" }
     ]
    },
    {
     "alias": "Indi- $tag_dlid ",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "f", "operator": "=", "value": "kWh_Day_Active" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/.*Inv*./" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2CC4" }
     ]
    },
    {
     "alias": "Anagodu Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *12910" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74D5C6CF2D57" },
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" }
     ]
    },
    {
     "alias": "Muttagi Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *6451" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90F9824B1" }
     ]
    },
    {
     "alias": "Indi Expected - $tag_dlid",
     "groupBy": [
      { "params": [ "1d,-330m" ], "type": "time" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *6851" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "f", "operator": "=", "value": "Day_Irradiance" },
      { "condition": "AND", "key": "dlid", "operator": "=", "value": "74C90FAFFAB3" }
     ]
    }
   ]
  },
  {
   "title": "Fleet Wise -Monthly Generation Reports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 }
  },
  {
   "title": "Plant Wise - Yearly Generation",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.year,\r\n    -- Expected Energy per plant\r\n    SUM(CASE WHEN w.plantid = 23 THEN w.Expected_Energy END) AS Expected_Energy_23,\r\n    SUM(CASE WHEN w.plantid = 24 THEN w.Expected_Energy END) AS Expected_Energy_24,\r\n    SUM(CASE WHEN w.plantid = 29 THEN w.Expected_Energy END) AS Expected_Energy_29,\r\n    SUM(CASE WHEN w.plantid = 30 THEN w.Expected_Energy END) AS Expected_Energy_30,\r\n    -- Total Generation per plant\r\n    SUM(CASE WHEN g.plantid = 23 THEN g.total_generation END) AS total_generation_23,\r\n    SUM(CASE WHEN g.plantid = 24 THEN g.total_generation END) AS total_generation_24,\r\n    SUM(CASE WHEN g.plantid = 29 THEN g.total_generation END) AS total_generation_29,\r\n    SUM(CASE WHEN g.plantid = 30 THEN g.total_generation END) AS total_generation_30,\r\n    -- DC Capacity per plant\r\n    MAX(CASE WHEN w.plantid = 23 THEN w.Dccapacity END) AS Dccapacity_23,\r\n    MAX(CASE WHEN w.plantid = 24 THEN w.Dccapacity END) AS Dccapacity_24,\r\n    MAX(CASE WHEN w.plantid = 29 THEN w.Dccapacity END) AS Dccapacity_29,\r\n    MAX(CASE WHEN w.plantid = 30 THEN w.Dccapacity END) AS Dccapacity_30,\r\n    -- Day Irradiation per plant\r\n    SUM(CASE WHEN w.plantid = 23 THEN w.dayIrradiation END) AS dayIrradiation_23,\r\n    SUM(CASE WHEN w.plantid = 24 THEN w.dayIrradiation END) AS dayIrradiation_24,\r\n    SUM(CASE WHEN w.plantid = 29 THEN w.dayIrradiation END) AS dayIrradiation_29,\r\n    SUM(CASE WHEN w.plantid = 30 THEN w.dayIrradiation END) AS dayIrradiation_30,\r\n    /* Specific Yield per plant (kWh/kW) */\r\n    MAX(CASE WHEN w.plantid = 23 THEN g.Specific_Yield END) AS SpecificYield_23,\r\n    MAX(CASE WHEN w.plantid = 24 THEN g.Specific_Yield END) AS SpecificYield_24,\r\n    MAX(CASE WHEN w.plantid = 29 THEN g.Specific_Yield END) AS SpecificYield_29,\r\n    MAX(CASE WHEN w.plantid = 30 THEN g.Specific_Yield END) AS SpecificYield_30\r\n   \r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        pi.Dccapacity,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y') AS year,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy,\r\n        SUM(ws.dayIrradiation) AS dayIrradiation\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid IN (23, 24, 29, 30)\r\n    GROUP BY ws.plantid, ws.plantname, pi.Dccapacity, year\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        pi.Dccapacity,  \r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y') AS year,\r\n        SUM(ig.daygeneration / (pi.Dccapacity * 1000)) AS Specific_Yield,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2))) as total_generation\r\n    FROM invgeneration ig\r\n    INNER JOIN plantinfo pi\r\n       ON ig.plantid = pi.plantid\r\n    WHERE ig.plantid IN (23, 24, 29, 30)\r\n    GROUP BY ig.plantid, ig.plantname, pi.Dccapacity, year\r\n) g\r\n    ON w.plantid = g.plantid AND w.year = g.year\r\nGROUP BY w.year\r\nORDER BY w.year;\r\n"
    }
   ]
  },
  {
   "title": "Plant Wise - Monthly Generation",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.month,\r\n    -- Expected Energy per plant\r\n    SUM(CASE WHEN w.plantid = 23 THEN w.Expected_Energy END) AS Expected_Energy_23,\r\n    SUM(CASE WHEN w.plantid = 24 THEN w.Expected_Energy END) AS Expected_Energy_24,\r\n    SUM(CASE WHEN w.plantid = 29 THEN w.Expected_Energy END) AS Expected_Energy_29,\r\n    SUM(CASE WHEN w.plantid = 30 THEN w.Expected_Energy END) AS Expected_Energy_30,\r\n    -- Total Generation per plant\r\n    SUM(CASE WHEN g.plantid = 23 THEN g.total_generation END) AS total_generation_23,\r\n    SUM(CASE WHEN g.plantid = 24 THEN g.total_generation END) AS total_generation_24,\r\n    SUM(CASE WHEN g.plantid = 29 THEN g.total_generation END) AS total_generation_29,\r\n    SUM(CASE WHEN g.plantid = 30 THEN g.total_generation END) AS total_generation_30,\r\n    -- DC Capacity per plant\r\n    MAX(CASE WHEN w.plantid = 23 THEN w.Dccapacity END) AS Dccapacity_23,\r\n    MAX(CASE WHEN w.plantid = 24 THEN w.Dccapacity END) AS Dccapacity_24,\r\n    MAX(CASE WHEN w.plantid = 29 THEN w.Dccapacity END) AS Dccapacity_29,\r\n    MAX(CASE WHEN w.plantid = 30 THEN w.Dccapacity END) AS Dccapacity_30,\r\n    -- Day Irradiation per plant\r\n    SUM(CASE WHEN w.plantid = 23 THEN w.dayIrradiation END) AS dayIrradiation_23,\r\n    SUM(CASE WHEN w.plantid = 24 THEN w.dayIrradiation END) AS dayIrradiation_24,\r\n    SUM(CASE WHEN w.plantid = 29 THEN w.dayIrradiation END) AS dayIrradiation_29,\r\n    SUM(CASE WHEN w.plantid = 30 THEN w.dayIrradiation END) AS dayIrradiation_30,\r\n    /* Specific Yield per plant (kWh/kW) */\r\n    MAX(CASE WHEN w.plantid = 23 THEN g.Specific_Yield END) AS SpecificYield_23,\r\n    MAX(CASE WHEN w.plantid = 24 THEN g.Specific_Yield END) AS SpecificYield_24,\r\n    MAX(CASE WHEN w.plantid = 29 THEN g.Specific_Yield END) AS SpecificYield_29,\r\n    MAX(CASE WHEN w.plantid = 30 THEN g.Specific_Yield END) AS SpecificYield_30\r\n   \r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        pi.Dccapacity,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy,\r\n        SUM(ws.dayIrradiation) AS dayIrradiation\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid IN (23, 24, 29, 30)\r\n    GROUP BY ws.plantid, ws.plantname, pi.Dccapacity, month\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        pi.Dccapacity,  \r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2)) / (pi.Dccapacity * 1000)) AS Specific_Yield,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2))) as total_generation\r\n    FROM invgeneration ig\r\n    INNER JOIN plantinfo pi\r\n       ON ig.plantid = pi.plantid\r\n    WHERE ig.plantid IN (23, 24, 29, 30)\r\n    GROUP BY ig.plantid, ig.plantname, pi.Dccapacity, month\r\n) g\r\n    ON w.plantid = g.plantid AND w.month = g.month\r\nGROUP BY w.month\r\nORDER BY w.month;\r\n"
    }
   ]
  },
  {
   "title": " Inverter wise - Monthly Generation",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(DATE_FORMAT(FROM_UNIXTIME(createddate + 86400), '%Y-%m-01'), '%Y-%m-%d') AS time,\r\n  CONCAT(plantname, '_', devicetype) AS plant_inverter,\r\n  SUM(CAST(REPLACE(daygeneration, ',', '') AS DECIMAL(10,2))) AS kWh_\r\nFROM invgeneration\r\nWHERE plantid IN (23,24,29,30)\r\nGROUP BY time, plant_inverter\r\nORDER BY time, plant_inverter;\r\n"
    }
   ]
  },
  {
   "title": " Inverter wise Specific Yield (kWh/kW) - Monthly Generation",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    STR_TO_DATE(DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y-%m-01'), '%Y-%m-%d') AS time,\r\n    CONCAT(ig.plantname, '_', di.devicetype) AS plant_inverter,\r\n    SUM(\r\n        CAST(REPLACE(NULLIF(CAST(REPLACE(NULLIF(ig.daygeneration, 'NA'), ',', '') AS DECIMAL(10,2)),'NA'),',','') AS DECIMAL(10,2)) \r\n        / NULLIF(di.Capacity,0)\r\n    ) AS SY_   -- Specific Yield per inverter\r\nFROM invgeneration ig\r\nINNER JOIN deviceinfo di\r\n    ON ig.plantid = di.plantid\r\n    AND ig.devicetype = di.devicetype\r\nWHERE ig.plantid IN (23, 24, 29, 30)\r\nGROUP BY time, plant_inverter\r\nORDER BY time, plant_inverter;\r\n"
    }
   ]
  }
 ]
}