{
 "title": "15.Slotwise Report Sample",
 "tags": [ "CMS" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "plant_name",
    "label": "Plant_name",
    "query": "PMPPL_Block01, PMPPL_Block02, PSPPL _MUTTAGI,PSPPL _INDI"
   }
  ]
 },
 "panels": [
  {
   "title": "Daily Slotwise Report ",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select plantname,\nDATE_FORMAT(FROM_UNIXTIME(createddate), '%Y-%m-%d') AS day,\nSUM(morning) AS Morning_Peak,\nSUM(afternoon) AS Normal_Hour,\nSUM(evening) AS Evening_Peak\nfrom invhourgeneration where plantname IN ($plant_name)\nGROUP BY day, plantname \nORDER BY plantname;\n"
    }
   ]
  },
  {
   "title": "Monthly Slotwise Report ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "select plantname,\nDATE_FORMAT(FROM_UNIXTIME(createddate), '%Y-%m') AS month,\nSUM(morning) AS Morning_Peak,\nSUM(afternoon) AS Normal_Hour,\nSUM(evening) AS Evening_Peak\nfrom invhourgeneration where plantid IN ('23','24','29','30')\nGROUP BY month, plantname \nORDER BY month, plantname;\n"
    }
   ]
  },
  {
   "title": "Year wise Slotwise Report ",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "select plantname,\nDATE_FORMAT(FROM_UNIXTIME(createddate), '%Y') AS year,\nSUM(morning) AS Morning_Peak,\nSUM(afternoon) AS Normal_Hour,\nSUM(evening) AS Evening_Peak\nfrom invhourgeneration where plantid IN ('23','24','29','30')\nGROUP BY year, plantname \nORDER BY plantname ASC;\n"
    }
   ]
  }
 ]
}