{
 "title": "11.Alerts Explorer View",
 "tags": [ "CMS" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "plant_name",
    "label": "Plant Name",
    "query": "Pemmasani Mayuukha Power Pvt Ltd, PSPPL_MUTTAGI, PSPPL_INDI"
   },
   {
    "name": "alert_type",
    "label": "Alert_type",
    "query": "SELECT DISTINCT alert_type\nFROM alert_logs\nWHERE plant_name IN (${plant_name})\n  AND alert_type NOT IN ('Day_Irradiance_Loss', 'Pyranometer_Issue', 'WMS_Loss')\nORDER BY alert_type;\n"
   },
   {
    "name": "device_id",
    "label": "Device ID",
    "query": "SELECT DISTINCT device_id FROM alert_logs WHERE plant_name IN (${plant_name}) ORDER BY device_id;"
   },
   {
    "name": "alert",
    "label": "Alert_Message",
    "query": "SELECT DISTINCT alert FROM alert_logs WHERE plant_name IN (${plant_name}) AND alert_type IN (${alert_type}) ORDER BY alert;"
   },
   {
    "name": "dlid",
    "label": "Plants",
    "query": " PSPPL_INDI_WMS : 74C90FAFFAB3 , PSPPL_INDI : 74D5C6CF2CC4,PMPPL_B01(6.00MW) : 44B7D09EA775, PMPPL_B02(6.01MW) : 44B7D09EA7C2, PMPPL_WMS : 74D5C6CF2D57,PSPPL_MUTTAGI :  44B7D09EA719, PSPPL_MUTTAGI_WMS : 74C90F9824B1"
   },
   {
    "name": "Devices",
    "label": "Devices",
    "query": "SHOW TAG VALUES FROM \"wattmon_std_mv\" WITH KEY IN (did) WHERE \"dlid\" =~ /$dlid/"
   },
   {
    "name": "Fields",
    "label": "Fields",
    "query": "SHOW TAG VALUES FROM \"wattmon_std_mv\" WITH KEY IN(f) WHERE \"dlid\" =~ /$dlid/ and \"did\" =~ /$Devices/"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  plant_name AS Plant,\r\n  alert AS `Alert Message`,\r\n  alert_type AS `Type`,\r\n  COUNT(*) AS `Alert Count`\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`) AND plant_name IN ($plant_name) \r\nGROUP BY plant_name, alert, alert_type\r\nORDER BY `Alert Count` DESC;\r\n"
    }
   ]
  },
  {
   "title": "Device Communication Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT plant_name, COUNT(*) AS \"Alert Count\"\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert_type = 'Communication Loss'\r\nGROUP BY plant_name\r\nORDER BY \"Alert Count\" DESC;"
    }
   ]
  },
  {
   "title": "Production Loss Alerts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT plant_name, COUNT(*) AS \"Alert Count\"\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert_type = 'Production Loss'\r\nGROUP BY plant_name\r\nORDER BY \"Alert Count\" DESC;"
    }
   ]
  },
  {
   "title": "Grid /Meter Failure",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT plant_name, COUNT(*) AS \"Alert Count\"\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert_type = 'Grid Loss/Meter Failure'\r\nGROUP BY plant_name\r\nORDER BY \"Alert Count\" DESC;"
    }
   ]
  },
  {
   "title": "VCB OFF",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT plant_name, COUNT(*) AS \"Alert Count\"\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert_type = 'VCB OFF'\r\nGROUP BY plant_name\r\nORDER BY \"Alert Count\" DESC;"
    }
   ]
  },
  {
   "title": "Wms Loss",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT plant_name, COUNT(*) AS \"Alert Count\"\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert_type = 'Wms Issue'\r\nGROUP BY plant_name\r\nORDER BY \"Alert Count\" DESC;"
    }
   ]
  },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 9, "x": 15, "y": 0 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 4, "x": 15, "y": 2 } },
  { "type": "volkovlabs-variable-panel", "gridPos": { "h": 2, "w": 5, "x": 19, "y": 2 } },
  {
   "title": "Alerts Explorer",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  FROM_UNIXTIME(`timestamp`) AS Time,\r\n  datalogger_id AS MAC,\r\n  device_id AS device_id,\r\n  plant_name AS Plant,\r\n  alert AS `Alert Message`,\r\n  event_code AS `Event Code`,\r\n  status_code AS `Status Code`,\r\n  mobile AS Recipient,\r\n  alert_type AS `Type`\r\nFROM alert_logs\r\nWHERE $__unixEpochFilter(`timestamp`)\r\n  AND plant_name IN ($plant_name)\r\n  AND alert IN ($alert)\r\n  AND alert_type IN ($alert_type)\r\n  AND device_id IN ($device_id)\r\nORDER BY Time DESC;\r\n"
    }
   ]
  },
  {
   "title": "Graphical view",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_did $tag_f",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "dlid" ], "type": "tag" },
      { "params": [ "did" ], "type": "tag" },
      { "params": [ "f" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "wattmon_std_mv",
     "query": "SELECT last(\"value\") FROM \"wattmon_std_mv\" WHERE (\"did\" =~ /^$Devices$/ AND \"f\" =~ /^$Fields$/ AND \"dlid\" =~ /^$dlid$/) AND $timeFilter GROUP BY time(5m), \"dlid\", \"did\", \"f\" fill(none)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "dlid", "operator": "=~", "value": "/^$dlid$/" },
      { "condition": "AND", "key": "did", "operator": "=~", "value": "/^$Devices$/" },
      { "condition": "AND", "key": "f", "operator": "=~", "value": "/^$Fields$/" }
     ]
    }
   ]
  }
 ]
}