{
 "title": "12.Monthly & Yearly Generation Reports",
 "tags": [ "CMS" ],
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "plant_name",
    "label": "Plants",
    "query": "PMPPLB01 : 23, PMPPLB02 : 24, PSPPLL_MUTTAGI : 29, PSPPL_INDI :  30"
   }
  ]
 },
 "panels": [
  {
   "title": "Plant Wise - Yearly Generation",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.plantname,\r\n    w.year,\r\n    w.total_dayIrradiation,\r\n    pi.Dccapacity,\r\n    g.total_generation,\r\n    w.Expected_Energy\r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y') AS year,\r\n        SUM(ws.dayIrradiation) AS total_dayIrradiation,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid = $plant_name\r\n    GROUP BY ws.plantid, ws.plantname, year, pi.Dccapacity\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y') AS year,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2))) as total_generation\r\n    FROM invgeneration ig\r\n    WHERE ig.plantid = $plant_name\r\n    GROUP BY ig.plantid, ig.plantname, year\r\n) g\r\nON w.plantid = g.plantid AND w.year = g.year\r\nINNER JOIN plantinfo pi\r\nON w.plantid = pi.plantid\r\nORDER BY w.plantname, w.year;\r\n"
    }
   ]
  },
  {
   "title": "Plant Wise - Monthly Generation",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.plantname,\r\n    w.month,\r\n    pi.Dccapacity,\r\n    w.total_dayIrradiation,\r\n    g.total_generation,\r\n    w.Expected_Energy\r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(ws.dayIrradiation) AS total_dayIrradiation,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid = $plant_name\r\n    GROUP BY ws.plantid, ws.plantname, month, pi.Dccapacity\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2))) as total_generation\r\n    FROM invgeneration ig\r\n    WHERE ig.plantid = $plant_name\r\n    GROUP BY ig.plantid, ig.plantname, month\r\n) g\r\nON w.plantid = g.plantid AND w.month = g.month\r\nINNER JOIN plantinfo pi\r\nON w.plantid = pi.plantid\r\nORDER BY w.plantname\r\n"
    }
   ]
  },
  {
   "title": "Plant Wise - Yearly Generation",
   "type": "table",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.plantname,\r\n    w.year,\r\n    w.total_dayIrradiation,\r\n    pi.Dccapacity,\r\n    g.total_generation,\r\n    w.Expected_Energy\r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y') AS year,\r\n        SUM(ws.dayIrradiation) AS total_dayIrradiation,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid = $plant_name\r\n    GROUP BY ws.plantid, ws.plantname, year, pi.Dccapacity\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y') AS year,\r\n        SUM(CAST(REPLACE(ig.daygeneration, ',', '') AS DECIMAL(10,2))) as total_generation\r\n    FROM invgeneration ig\r\n    WHERE ig.plantid = $plant_name\r\n    GROUP BY ig.plantid, ig.plantname, year\r\n) g\r\nON w.plantid = g.plantid AND w.year = g.year\r\nINNER JOIN plantinfo pi\r\nON w.plantid = pi.plantid\r\nORDER BY w.plantname, w.year;\r\n"
    }
   ]
  },
  {
   "title": "Plant Wise - Monthiy Generation",
   "type": "table",
   "gridPos": { "h": 13, "w": 13, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    w.plantname,\r\n    w.month,\r\n    pi.Dccapacity,\r\n    w.total_dayIrradiation,\r\n    g.total_generation,\r\n    w.Expected_Energy\r\nFROM (\r\n    SELECT\r\n        ws.plantid,\r\n        ws.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ws.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(ws.dayIrradiation) AS total_dayIrradiation,\r\n        SUM(ws.dayIrradiation * (pi.Dccapacity * 1000)) AS Expected_Energy\r\n    FROM weatherstation ws\r\n    INNER JOIN plantinfo pi\r\n        ON ws.plantid = pi.plantid\r\n    WHERE ws.plantid = $plant_name\r\n    GROUP BY ws.plantid, ws.plantname, month, pi.Dccapacity\r\n) w\r\nINNER JOIN (\r\n    SELECT\r\n        ig.plantid,\r\n        ig.plantname,\r\n        DATE_FORMAT(FROM_UNIXTIME(ig.createddate + 86400), '%Y-%m') AS month,\r\n        SUM(ig.daygeneration) AS total_generation\r\n    FROM invgeneration ig\r\n    WHERE ig.plantid = $plant_name\r\n    GROUP BY ig.plantid, ig.plantname, month\r\n) g\r\nON w.plantid = g.plantid AND w.month = g.month\r\nINNER JOIN plantinfo pi\r\nON w.plantid = pi.plantid\r\nORDER BY w.plantname\r\n"
    }
   ]
  },
  {
   "title": " Inverter wise - Monthiy Generation",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(DATE_FORMAT(FROM_UNIXTIME(createddate + 86400), '%Y-%m-01'), '%Y-%m-%d') AS time,\r\n  devicetype AS inverter,\r\n  SUM(CAST(REPLACE(daygeneration, ',', '') AS DECIMAL(10,2))) AS total_generation\r\nFROM invgeneration\r\nWHERE plantid = $plant_name\r\nGROUP BY time, inverter\r\nORDER BY time, inverter;\r\n"
    }
   ]
  },
  {
   "title": " Inverter wise - Monthiy Generation",
   "type": "table",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  STR_TO_DATE(DATE_FORMAT(FROM_UNIXTIME(createddate + 86400), '%Y-%m-01'), '%Y-%m-%d') AS time,\r\n  devicetype AS inverter,\r\n  SUM(CAST(REPLACE(daygeneration, ',', '') AS DECIMAL(10,2))) AS total_generation\r\nFROM invgeneration\r\nWHERE plantid = $plant_name\r\nGROUP BY time, inverter\r\nORDER BY time, inverter;\r\n"
    }
   ]
  }
 ]
}